yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/comment/',
         views.add_comment, name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.page_not_found'

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

from core.models import CreatedModel

User = get_user_model()


class Group(models.Model):
    """Группы постов"""
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self) -> str:
        return self.title


class Post(CreatedModel):
    """Посты"""
    text = models.TextField(
        verbose_name='Текст поста',
        help_text='Введите текст поста'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        related_name='posts',
        blank=True,
        null=True,
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True,
        help_text='Загрузить картинку'
    )

    class Meta:
        ordering = ['-created']
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.text[:15]


class Comment(CreatedModel):
    """Комментарии"""
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор комментария'
    )
    text = models.TextField(
        verbose_name='Текст комментария',
        help_text='Введите текст комментария'
    )

    class Meta:
        ordering = ['-created']
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return self.text[:15]


class Follow(models.Model):
    """Подписка на пользователя"""
    # User - Подписывается.
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower'
    )
    # Author - тот на кого подписываются.
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following'
    )

    class Meta:
        verbose_name = 'Подписка'
        verbose_name_plural = 'Подписки'

yatube/posts/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')

    def clean_text(self):
        text = self.cleaned_data.get('text')
        if not text:
            raise forms.ValidationError("Пост не может быть пустым")
        return text


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

    def clean_text(self):
        text = self.cleaned_data.get('text')
        if not text:
            raise forms.ValidationError("Комментарий не может быть пустым")
        return text

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page

from django.conf import settings
from .forms import PostForm, CommentForm
from .models import Group, Post, User, Follow


def get_paginated_page(request, queryset):
    """Пагинатор, выводит по 10 постов на странице."""
    paginator = Paginator(queryset, settings.POSTS_PER_PAGE)
    page_number = request.GET.get('page')
    return paginator.get_page(page_number)


@cache_page(20, key_prefix='index_page')
def index(request):
    """Главная страница."""
    posts = Post.objects.all().select_related('author', 'group')
    page_obj = get_paginated_page(request, posts)

    template = 'posts/index.html'

    context = {
        'title': 'Последние обновления на сайте',
        'page_obj': page_obj,
        'index': True,
    }
    return render(request, template, context)


def group_posts(request, slug):
    """Группы постов."""
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all().select_related('author')
    page_obj = get_paginated_page(request, posts)

    template = 'posts/group_list.html'

    context = {
        'group': group,
        'posts': posts,
        'title': f'Посты группы {group.title}',
        'page_obj': page_obj,
    }
    return render(request, template, context)


def profile(request, username):
    """Профиль пользователя."""
    user = get_object_or_404(User, username=username)
    user_posts = user.posts.all().select_related('author', 'group')
    page_obj = get_paginated_page(request, user_posts)

    # Проверка на авторизацию.
    if request.user.is_authenticated:
        # Проверка на подписку.
        following_check = Follow.objects.filter(author=user, user=request.user)
        following = following_check.exists()
    else:
        following = False

    template = 'posts/profile.html'

    context = {
        'title': f'Профайл пользователя: {user.first_name} '
                 f'{user.last_name}',
        'page_obj': page_obj,
        'author': user,
        'following': following,
    }
    return render(request, template, context)


def post_detail(request, post_id):
    """Подробнее о посте."""
    post = get_object_or_404(
        Post.objects.select_related('author', 'group'), id=post_id
    )
    form = CommentForm()
    comments = post.comments.all()

    template = 'posts/post_detail.html'

    context = {
        'title': post.text[:30],
        'post': post,
        'form': form,
        'comments': comments,
    }
    return render(request, template, context)


@login_required
def add_comment(request, post_id):
    """Добавление комментария."""
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def post_create(request):
    """Отправка поста."""
    form = PostForm(
        request.POST or None,
        files=request.FILES or None
    )

    if form.is_valid():
        new_post = form.save(commit=False)
        new_post.author = request.user
        new_post.save()
        return redirect('posts:profile', username=new_post.author)

    template = 'posts/create_post.html'

    context = {
        'title': 'Добавить запись',
        'form': form,
    }
    return render(request, template, context)


@login_required
def post_edit(request, post_id):
    """Редактирование поста."""
    post = get_object_or_404(Post, id=post_id)

    if post.author != request.user:
        return redirect('posts:post_detail', post_id=post.id)

    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post,
    )

    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post.id)

    template = 'posts/create_post.html'

    context = {
        'title': 'Редактировать запись',
        'is_edit': True,
        'form': form,
        'post': post,
    }
    return render(request, template, context)


@login_required
def follow_index(request):
    """Персональная лента."""

    # Получаем id авторов, на которых подписан пользователь.
    followed_authors = Follow.objects.filter(
        user_id=request.user.id
    ).values_list('author_id')

    # Получаем посты этих авторов,
    # author, и group нужны в карточке поста.
    post_list = Post.objects.filter(
        author__in=followed_authors
    ).select_related('author', 'group')

    page_obj = get_paginated_page(request, post_list)

    context = {
        'title': 'Персональная лента',
        'page_obj': page_obj,
        'follow': True
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    """Кнопка Подписаться"""
    author = get_object_or_404(User, username=username)
    # Подписаться на пользователя можно только один раз.
    # Подписаться на себя нельзя.
    check = Follow.objects.filter(user=request.user, author=author).exists()
    if request.user != author and check is False:
        Follow.objects.create(user=request.user, author=author)
    return redirect('posts:profile', username=author.username)


@login_required
def profile_unfollow(request, username):
    """Кнопка Отписаться"""
    author = get_object_or_404(User, username=username)
    Follow.objects.filter(user=request.user, author=author).delete()
    return redirect('posts:profile', username=author.username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block  content %}
  {% load user_filters %}

  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">

          {% if is_edit %}
            Редактировать пост
          {% else %}
            Новый пост
          {% endif %}

        </div>
        <div class="card-body">

          {% if form.errors %}
            {% for field in form %}
              {% for error in field.errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
              <div class="alert alert-danger">
                {{ error|escape }}
              </div>
            {% endfor %}
          {% endif %}

          {% if is_edit %}
            <form method="post" enctype="multipart/form-data"
                  action="{% url 'posts:post_edit' post_id=post.id %}">
          {% else %}
            <form method="post" enctype="multipart/form-data"
                  action="{% url 'posts:post_create' %}">
          {% endif %}

          {% csrf_token %}

          {% for field in form %}
            <div class="form-group row my-3"
                    {% if field.field.required %}
                 aria-required="true"
                    {% else %}
                 aria-required="false"
                    {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                {% if field.field.required %}
                  <span class="required text-danger">*</span>
                {% endif %}
              </label>
              <div>
                {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help"
                         class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}

          <div class="d-flex justify-content-end">
            <button type="submit" class="btn btn-primary">

              {% if is_edit %}
                Сохранить
              {% else %}
                Добавить
              {% endif %}

            </button>
          </div>
          </form>
        </div>
      </div>
    </div>
  </div>


{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% block  content %}

  <h1>{{ title }}</h1>

  {% include 'posts/includes/switcher.html' %}
  {% for post in page_obj %}
    {% include 'posts/includes/card.html' %}

    {% if post.group %}
      <a href="{% url 'posts:group_list' post.group.slug %}">все
        записи группы</a>
    {% endif %}

    {% if not forloop.last %}
      <hr>{% endif %}

  {% endfor %}

  {% include 'posts/includes/paginator.html' %}

{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block  content %}
  {% load thumbnail %}
  {% for post in page_obj %}
    {% if forloop.first %}

      <h1>{{ post.group.title }}</h1>
      <p>{{ post.group.description }}</p>
    {% endif %}

    {% include 'posts/includes/card.html' %}

    {% if not forloop.last %}
      <hr>{% endif %}


  {% endfor %}
  {% include 'posts/includes/paginator.html' %}

{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block  content %}
  <h1>{{ title }}</h1>

  {% include 'posts/includes/switcher.html' %}

  {% for post in page_obj %}
    {% include 'posts/includes/card.html' %}

    {% if post.group %}
      <a href="{% url 'posts:group_list' post.group.slug %}">все
        записи группы</a>
    {% endif %}

    {% if not forloop.last %}
      <hr>{% endif %}

  {% endfor %}

  {% include 'posts/includes/paginator.html' %}

{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block  content %}
  {% load user_filters %}
  {% load thumbnail %}

  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post.created|date:"d E Y" }}
        </li>
        {% if post.group %}
          <li class="list-group-item">
            Группа: {{ post.group.title }}
            <a href="{% url 'posts:group_list' post.group.slug %}">
              <p>все записи группы</a>
          </li>
        {% endif %}
        <li class="list-group-item">
          Автор: {{ post.author.get_full_name }}
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора:
          <span>{{ post.author.posts.count }}</span>
        </li>
        <li class="list-group-item">
          <a href="{% url 'posts:profile' post.author %}">все посты
            пользователя</a>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}"
             alt="here must be an image">
      {% endthumbnail %}
      <p>
        {{ post.text }}
      </p>
      {% if request.user == post.author %}
        <a class="btn btn-primary"
           href="{% url 'posts:post_edit' post_id=post.id %}">
          редактировать запись
        </a>
      {% endif %}


      {% if user.is_authenticated %}
        <div class="card my-4">
          <h5 class="card-header">Добавить комментарий:</h5>
          <div class="card-body">
            <form method="post"
                  action="{% url 'posts:add_comment' post_id=post.id %}">
              {% csrf_token %}
              <div class="form-group mb-2">

                {% for field in form %}
                  <div class="form-group row my-3"
                          {% if field.field.required %}
                       aria-required="true"
                          {% else %}
                       aria-required="false"
                          {% endif %}
                  >
                    <label for="{{ field.id_for_label }}">
                      {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                    </label>
                    <div>
                      {{ field|addclass:'form-control' }}
                      {% if field.help_text %}
                        <small id="{{ field.id_for_label }}-help"
                               class="form-text text-muted">
                          {{ field.help_text|safe }}
                        </small>
                      {% endif %}
                    </div>
                  </div>
                {% endfor %}

              </div>
              <button type="submit" class="btn btn-primary">
                Отправить
              </button>
            </form>
          </div>
        </div>
      {% endif %}

      {% for comment in comments %}
        <div class="media mb-4">
          <div class="media-body">
            <h5 class="mt-0">
              <a href="{% url 'posts:profile' comment.author.username %}">
                {{ comment.author.username }}
              </a>
            </h5>
            <p>
              {{ comment.text }}
            </p>
          </div>
        </div>
      {% endfor %}


    </article>
  </div>

{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block  content %}
  {% load thumbnail %}
  <div class="mb-5">

    <h1> {{ title }} </h1>
    <h3>Всего постов: {{ author.posts.count }} </h3>

    {% if request.user != author %}
      {% if following %}

        <a class="btn btn-lg btn-light"
           href="{% url 'posts:profile_unfollow' author.username %}"
           role="button">Отписаться</a>

      {% else %}

        <a class="btn btn-lg btn-primary"
           href="{% url 'posts:profile_follow' author.username %}"
           role="button">Подписаться</a>

      {% endif %}
    {% endif %}

  </div>

  {% for post in page_obj %}

    {% include 'posts/includes/card.html' %}

    {% if post.group %}
      <a href="{% url 'posts:group_list' post.group.slug %}">все
        записи группы</a>
    {% endif %}

    {% if not forloop.last %}
      <hr>{% endif %}

  {% endfor %}
  {% include 'posts/includes/paginator.html' %}

{% endblock %}